apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: bombmaster
    name: bombmaster
spec:
    replicas: 1
    selector:
        matchLabels:
            app: bombmaster
    template:
        metadata:
            labels:
                app: bombmaster
        spec:
            containers:
                - image: rcpooley/bombmaster:latest
                  imagePullPolicy: Always
                  name: bombmaster
                  ports:
                      - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
    labels:
        app: bombmaster
    name: bombmaster
spec:
    type: NodePort
    ports:
        - port: 8080
          nodePort: 30123
    selector:
        app: bombmaster
